package evaluationserver.server.execution;

import evaluationserver.server.entities.File;
import evaluationserver.server.entities.Language;
import evaluationserver.server.entities.Solution;
import evaluationserver.server.entities.SystemReply;
import evaluationserver.server.entities.Task;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.EntityManager;
import org.springframework.beans.factory.BeanFactory;
import org.springframework.beans.factory.xml.XmlBeanFactory;
import org.springframework.core.io.FileSystemResource;
import org.springframework.core.io.Resource;

public class FillData {
	public static void main(String[] args) throws Exception {
		
		String diff = 
"f0VMRgEBAQAAAAAAAAAAAAIAAwABAAAAcIMECDQAAABkEQAAAAAAADQAIAAJACgAHgAbAAYAAAA0"+
"AAAANIAECDSABAggAQAAIAEAAAUAAAAEAAAAAwAAAFQBAABUgQQIVIEECBMAAAATAAAABAAAAAEA"+
"AAABAAAAAAAAAACABAgAgAQIVAUAAFQFAAAFAAAAABAAAAEAAAD8DgAA/J4ECPyeBAgYAQAAIAEA"+
"AAYAAAAAEAAAAgAAABAPAAAQnwQIEJ8ECOAAAADgAAAABgAAAAQAAAAEAAAAaAEAAGiBBAhogQQI"+
"RAAAAEQAAAAEAAAABAAAAFDldGQEBQAABIUECASFBAgUAAAAFAAAAAQAAAAEAAAAUeV0ZAAAAAAA"+
"AAAAAAAAAAAAAAAAAAAABgAAAAQAAABS5XRk/A4AAPyeBAj8ngQIBAEAAAQBAAAEAAAAAQAAAC9s"+
"aWIvbGQtbGludXguc28uMgAABAAAABAAAAABAAAAR05VAAAAAAACAAAABgAAAA8AAAAEAAAAFAAA"+
"AAMAAABHTlUAedPwTQPgUh72pIYlbc6H8ncBWYACAAAABQAAAAEAAAAFAAAAACAAIAAAAAAFAAAA"+
"rUvjwAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAgAAAAHwAAAAAAAAAAAAAAIAAAAGsAAAAA"+
"AAAAAAAAABIAAABkAAAAAAAAAAAAAAASAAAAVQAAAPyEBAgEAAAAEQAPAABsaWJzdGRjKysuc28u"+
"NgBfX2dtb25fc3RhcnRfXwBfSnZfUmVnaXN0ZXJDbGFzc2VzAGxpYm0uc28uNgBsaWJnY2Nfcy5z"+
"by4xAGxpYmMuc28uNgBfSU9fc3RkaW5fdXNlZABwcmludGYAX19saWJjX3N0YXJ0X21haW4AR0xJ"+
"QkNfMi4wAAAAAAAAAAACAAIAAQABAAEASwAAABAAAAAAAAAAEGlpDQAAAgB9AAAAAAAAAPCfBAgG"+
"AQAAAKAECAcBAAAEoAQIBwMAAAigBAgHBAAAVYnlU4PsBOgAAAAAW4HD6BwAAIuT/P///4XSdAXo"+
"HgAAAOjZAAAA6IQBAABYW8nD/zX4nwQI/yX8nwQIAAAAAP8lAKAECGgAAAAA6eD/////JQSgBAho"+
"CAAAAOnQ/////yUIoAQIaBAAAADpwP///zHtXonhg+TwUFRSaKCEBAhoQIQECFFWaCSEBAjov///"+
"//SQkJCQkJCQkJCQkJCQkFWJ5VOD7ASAPRSgBAgAdT+hGKAECLsInwQIgesEnwQIwfsCg+sBOdhz"+
"Ho22AAAAAIPAAaMYoAQI/xSFBJ8ECKEYoAQIOdhy6MYFFKAECAGDxARbXcONdCYAjbwnAAAAAFWJ"+
"5YPsGKEMnwQIhcB0ErgAAAAAhcB0CccEJAyfBAj/0MnDkFWJ5YPk8IPsEMcEJACFBAjoJ////7gA"+
"AAAAycNVieVXVlPoWgAAAIHDqRsAAIPsHOin/v//jbsI////jYMI////KcfB/wKF/3QkMfaLRRCJ"+
"RCQIi0UMiUQkBItFCIkEJP+Uswj///+DxgE5/nLeg8QcW15fXcONtgAAAABVieVdw4scJMOQkJCQ"+
"kJCQVYnlU4PsBKH8ngQIg/j/dBO7/J4ECGaQg+sE/9CLA4P4/3X0g8QEW13DkJBVieVTg+wE6AAA"+
"AABbgcMMGwAA6Kz+//9ZW8nDAwAAAAEAAgBBQwAAARsDOxAAAAABAAAAIP///ywAAAAUAAAAAAAA"+
"AAF6UgABfAgBGwwEBIgBAAAcAAAAHAAAAOz+//8cAAAAAEEOCEKFAg0FWMUMBAQAAAAAAAAAAAAA"+
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
"AAAAAAAAAAAAAAAAAAAAAAD/////AAAAAP////8AAAAAAAAAAAEAAAABAAAAAQAAADMAAAABAAAA"+
"PQAAAAEAAABLAAAADAAAAACDBAgNAAAA3IQECPX+/2+sgQQIBQAAACyCBAgGAAAAzIEECAoAAACH"+
"AAAACwAAABAAAAAVAAAAAAAAAAMAAAD0nwQIAgAAABgAAAAUAAAAEQAAABcAAADoggQIEQAAAOCC"+
"BAgSAAAACAAAABMAAAAIAAAA/v//b8CCBAj///9vAQAAAPD//2+0ggQIAAAAAAAAAAAAAAAAAAAA"+
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABCfBAgAAAAAAAAAAEaDBAhWgwQI"+
"ZoMECAAAAAAAAAAAR0NDOiAoVWJ1bnR1L0xpbmFybyA0LjUuMi04dWJ1bnR1NCkgNC41LjIAR0ND"+
"OiAoVWJ1bnR1L0xpbmFybyA0LjUuMi04dWJ1bnR1MykgNC41LjIAAC5zeW10YWIALnN0cnRhYgAu"+
"c2hzdHJ0YWIALmludGVycAAubm90ZS5BQkktdGFnAC5ub3RlLmdudS5idWlsZC1pZAAuZ251Lmhh"+
"c2gALmR5bnN5bQAuZHluc3RyAC5nbnUudmVyc2lvbgAuZ251LnZlcnNpb25fcgAucmVsLmR5bgAu"+
"cmVsLnBsdAAuaW5pdAAudGV4dAAuZmluaQAucm9kYXRhAC5laF9mcmFtZV9oZHIALmVoX2ZyYW1l"+
"AC5jdG9ycwAuZHRvcnMALmpjcgAuZHluYW1pYwAuZ290AC5nb3QucGx0AC5kYXRhAC5ic3MALmNv"+
"bW1lbnQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABsAAAABAAAAAgAA"+
"AFSBBAhUAQAAEwAAAAAAAAAAAAAAAQAAAAAAAAAjAAAABwAAAAIAAABogQQIaAEAACAAAAAAAAAA"+
"AAAAAAQAAAAAAAAAMQAAAAcAAAACAAAAiIEECIgBAAAkAAAAAAAAAAAAAAAEAAAAAAAAAEQAAAD2"+
"//9vAgAAAKyBBAisAQAAIAAAAAUAAAAAAAAABAAAAAQAAABOAAAACwAAAAIAAADMgQQIzAEAAGAA"+
"AAAGAAAAAQAAAAQAAAAQAAAAVgAAAAMAAAACAAAALIIECCwCAACHAAAAAAAAAAAAAAABAAAAAAAA"+
"AF4AAAD///9vAgAAALSCBAi0AgAADAAAAAUAAAAAAAAAAgAAAAIAAABrAAAA/v//bwIAAADAggQI"+
"wAIAACAAAAAGAAAAAQAAAAQAAAAAAAAAegAAAAkAAAACAAAA4IIECOACAAAIAAAABQAAAAAAAAAE"+
"AAAACAAAAIMAAAAJAAAAAgAAAOiCBAjoAgAAGAAAAAUAAAAMAAAABAAAAAgAAACMAAAAAQAAAAYA"+
"AAAAgwQIAAMAADAAAAAAAAAAAAAAAAQAAAAAAAAAhwAAAAEAAAAGAAAAMIMECDADAABAAAAAAAAA"+
"AAAAAAAEAAAABAAAAJIAAAABAAAABgAAAHCDBAhwAwAAbAEAAAAAAAAAAAAAEAAAAAAAAACYAAAA"+
"AQAAAAYAAADchAQI3AQAABwAAAAAAAAAAAAAAAQAAAAAAAAAngAAAAEAAAACAAAA+IQECPgEAAAL"+
"AAAAAAAAAAAAAAAEAAAAAAAAAKYAAAABAAAAAgAAAASFBAgEBQAAFAAAAAAAAAAAAAAABAAAAAAA"+
"AAC0AAAAAQAAAAIAAAAYhQQIGAUAADwAAAAAAAAAAAAAAAQAAAAAAAAAvgAAAAEAAAADAAAA/J4E"+
"CPwOAAAIAAAAAAAAAAAAAAAEAAAAAAAAAMUAAAABAAAAAwAAAASfBAgEDwAACAAAAAAAAAAAAAAA"+
"BAAAAAAAAADMAAAAAQAAAAMAAAAMnwQIDA8AAAQAAAAAAAAAAAAAAAQAAAAAAAAA0QAAAAYAAAAD"+
"AAAAEJ8ECBAPAADgAAAABgAAAAAAAAAEAAAACAAAANoAAAABAAAAAwAAAPCfBAjwDwAABAAAAAAA"+
"AAAAAAAABAAAAAQAAADfAAAAAQAAAAMAAAD0nwQI9A8AABgAAAAAAAAAAAAAAAQAAAAEAAAA6AAA"+
"AAEAAAADAAAADKAECAwQAAAIAAAAAAAAAAAAAAAEAAAAAAAAAO4AAAAIAAAAAwAAABSgBAgUEAAA"+
"CAAAAAAAAAAAAAAABAAAAAAAAADzAAAAAQAAADAAAAAAAAAAFBAAAFQAAAAAAAAAAAAAAAEAAAAB"+
"AAAAEQAAAAMAAAAAAAAAAAAAAGgQAAD8AAAAAAAAAAAAAAABAAAAAAAAAAEAAAACAAAAAAAAAAAA"+
"AAAUFgAAEAQAAB0AAAAtAAAABAAAABAAAAAJAAAAAwAAAAAAAAAAAAAAJBoAAP8BAAAAAAAAAAAA"+
"AAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABUgQQIAAAAAAMAAQAAAAAAaIEECAAAAAADAAIA"+
"AAAAAIiBBAgAAAAAAwADAAAAAACsgQQIAAAAAAMABAAAAAAAzIEECAAAAAADAAUAAAAAACyCBAgA"+
"AAAAAwAGAAAAAAC0ggQIAAAAAAMABwAAAAAAwIIECAAAAAADAAgAAAAAAOCCBAgAAAAAAwAJAAAA"+
"AADoggQIAAAAAAMACgAAAAAAAIMECAAAAAADAAsAAAAAADCDBAgAAAAAAwAMAAAAAABwgwQIAAAA"+
"AAMADQAAAAAA3IQECAAAAAADAA4AAAAAAPiEBAgAAAAAAwAPAAAAAAAEhQQIAAAAAAMAEAAAAAAA"+
"GIUECAAAAAADABEAAAAAAPyeBAgAAAAAAwASAAAAAAAEnwQIAAAAAAMAEwAAAAAADJ8ECAAAAAAD"+
"ABQAAAAAABCfBAgAAAAAAwAVAAAAAADwnwQIAAAAAAMAFgAAAAAA9J8ECAAAAAADABcAAAAAAAyg"+
"BAgAAAAAAwAYAAAAAAAUoAQIAAAAAAMAGQAAAAAAAAAAAAAAAAADABoAAQAAAAAAAAAAAAAABADx"+
"/wwAAAD8ngQIAAAAAAEAEgAaAAAABJ8ECAAAAAABABMAKAAAAAyfBAgAAAAAAQAUADUAAACggwQI"+
"AAAAAAIADQBLAAAAFKAECAEAAAABABkAWgAAABigBAgEAAAAAQAZAGgAAAAAhAQIAAAAAAIADQAB"+
"AAAAAAAAAAAAAAAEAPH/dAAAAACfBAgAAAAAAQASAIEAAABQhQQIAAAAAAEAEQCPAAAADJ8ECAAA"+
"AAABABQAmwAAALCEBAgAAAAAAgANALEAAAAAAAAAAAAAAAQA8f+7AAAA9J8ECAAAAAABABcA0QAA"+
"APyeBAgAAAAAAAASAOIAAAD8ngQIAAAAAAAAEgD1AAAAEJ8ECAAAAAABABUA/gAAAAygBAgAAAAA"+
"IAAYAAkBAACghAQIBQAAABIADQAZAQAAcIMECAAAAAASAA0AIAEAAAAAAAAAAAAAIAAAAC8BAAAA"+
"AAAAAAAAACAAAABDAQAA+IQECAQAAAARAA8ASgEAANyEBAgAAAAAEgAOAFABAAAAAAAAAAAAABIA"+
"AABtAQAA/IQECAQAAAARAA8AfAEAAAygBAgAAAAAEAAYAIkBAAAQoAQIAAAAABECGACWAQAACJ8E"+
"CAAAAAARAhMAowEAAECEBAhaAAAAEgANALMBAAAAAAAAAAAAABIAAADFAQAAFKAECAAAAAAQAPH/"+
"0QEAABygBAgAAAAAEADx/9YBAAAUoAQIAAAAABAA8f/dAQAApYQECAAAAAASAg0A9AEAACSEBAgc"+
"AAAAEgANAPkBAAAAgwQIAAAAABIACwAAY3J0c3R1ZmYuYwBfX0NUT1JfTElTVF9fAF9fRFRPUl9M"+
"SVNUX18AX19KQ1JfTElTVF9fAF9fZG9fZ2xvYmFsX2R0b3JzX2F1eABjb21wbGV0ZWQuNjE1NQBk"+
"dG9yX2lkeC42MTU3AGZyYW1lX2R1bW15AF9fQ1RPUl9FTkRfXwBfX0ZSQU1FX0VORF9fAF9fSkNS"+
"X0VORF9fAF9fZG9fZ2xvYmFsX2N0b3JzX2F1eABmb3Blbi5jcHAAX0dMT0JBTF9PRkZTRVRfVEFC"+
"TEVfAF9faW5pdF9hcnJheV9lbmQAX19pbml0X2FycmF5X3N0YXJ0AF9EWU5BTUlDAGRhdGFfc3Rh"+
"cnQAX19saWJjX2NzdV9maW5pAF9zdGFydABfX2dtb25fc3RhcnRfXwBfSnZfUmVnaXN0ZXJDbGFz"+
"c2VzAF9mcF9odwBfZmluaQBfX2xpYmNfc3RhcnRfbWFpbkBAR0xJQkNfMi4wAF9JT19zdGRpbl91"+
"c2VkAF9fZGF0YV9zdGFydABfX2Rzb19oYW5kbGUAX19EVE9SX0VORF9fAF9fbGliY19jc3VfaW5p"+
"dABwcmludGZAQEdMSUJDXzIuMABfX2Jzc19zdGFydABfZW5kAF9lZGF0YQBfX2k2ODYuZ2V0X3Bj"+
"X3RodW5rLmJ4AG1haW4AX2luaXQA";

		String program = "#include <stdio.h>\nint main()\n{\nprintf(\"Hello World!\");\nreturn 0;\n}";
		
		Resource resource = new FileSystemResource("configuration.xml");
		BeanFactory factory = new XmlBeanFactory(resource);
		
		// get server instance
		EntityManager em = factory.getBean(EntityManager.class);
		
		Language langC = new Language(null, "C", "c", "c");
		Language langCpp = new Language(null, "C++", "cpp", "cpp");
		
		List<SystemReply> replies = new ArrayList<SystemReply>();
		for(Reply r : Reply.values())
			replies.add(new SystemReply(null, r.getName(), r.isAccepting(), r.getCode()));
		
//		java.io.File resolverFile = new java.io.File("../resolver");
//		byte[] bytes = new byte[(int)resolverFile.length()];
//		FileInputStream fis = new FileInputStream(resolverFile);
//		fis.read(bytes);
//		fis.close();
//		String s = new sun.misc.BASE64Encoder().encode(bytes);
		
		File fileResultResolver = new File(null, "diff", 10000).setData(new sun.misc.BASE64Decoder().decodeBuffer(diff));
		File inputData = new File(null, "solutionInputData", 10).setData("1 2 3 4 5".getBytes());

		Task task = new Task(null, "Task", "...", 3000, 50000, 5000000, 5000000, new Date()).setResultResolver(fileResultResolver).setInputData(inputData);
		
		File fileSolution = new File(null, "solution.c", 10000).setData(program.getBytes());
		File fileSolution2 = new File(null, "solution2.c", 10000).setData(program.getBytes());
		Solution solution = new Solution(null, new Date()).setLanguage(langC).setTask(task).setFile(fileSolution);
		Solution solution2 = new Solution(null, new Date()).setLanguage(langC).setTask(task).setFile(fileSolution2);
		
		Object[] entities = {
			langC,
			langCpp,
			fileResultResolver,
			inputData,
			task,
			fileSolution,
			solution,
			fileSolution2,
			solution2
		};
		
		em.getTransaction().begin();
		for(Object o : replies)
			em.persist(o);
		for(Object o : entities)
			em.persist(o);
		em.flush();
		em.getTransaction().commit();
	}	
}
